# Fix "resource temporarily unavailable" errors. These errors occurred after
# a Travis update to new Trusty images on Dec. 12th 2017. The reason for these
# errors is unknown. Using the deprecated builds did not fix the problem.
# Setting 'filter_secrets: false' as suggested here
# https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-321777557
# fixes the problem.
filter_secrets: false

# Handle Python installation and dependencies ourselves
language: cpp

# NOTE: Make sure the matrix covers all node types in top.sls
# NOTE: Make sure each node type is tested both from scratch and as an upgrade
# sudo: required and dist: trusty enable usage of Trusty
matrix:
  include:
    # Salt from scratch
    - env:
        - SALT_NODE_ID=servo-linux-cross1
        - SALT_FROM_SCRATCH=true
      os: linux
      sudo: required
      dist: trusty
    - env:
        - SALT_NODE_ID=servo-mac1
        - SALT_FROM_SCRATCH=true
      os: osx
      osx_image: xcode8
    - env:
        - SALT_NODE_ID=servo-linux1
        - SALT_FROM_SCRATCH=true
      os: linux
      sudo: required
      dist: trusty
    - env:
        - SALT_NODE_ID=servo-master1
        - SALT_FROM_SCRATCH=true
      os: linux
      sudo: required
      dist: trusty
    # Salt from previous configuration
    - env:
        - SALT_NODE_ID=servo-linux-cross1
        - SALT_FROM_SCRATCH=false
      os: linux
      sudo: required
      dist: trusty
    - env:
        - SALT_NODE_ID=servo-mac1
        - SALT_FROM_SCRATCH=false
      os: osx
      osx_image: xcode8
    - env:
        - SALT_NODE_ID=servo-linux1
        - SALT_FROM_SCRATCH=false
      os: linux
      sudo: required
      dist: trusty
    - env:
        - SALT_NODE_ID=servo-master1
        - SALT_FROM_SCRATCH=false
      os: linux
      sudo: required
      dist: trusty
    # Salt inside Docker
    - env:
        - SALT_NODE_ID=servo-linux1
        - SALT_FROM_SCRATCH=true
          # ubuntu/14.04
        - SALT_DOCKER_IMAGE=ubuntu@sha256:edf05697d8ea17028a69726b4b450ad48da8b29884cd640fec950c904bfb50ce
      os: linux
      sudo: required
      dist: trusty
    - env:
        - SALT_NODE_ID=servo-linux1
        - SALT_FROM_SCRATCH=true
          # ubuntu/16.04
        - SALT_DOCKER_IMAGE=ubuntu@sha256:f3a61450ae43896c4332bda5e78b453f4a93179045f20c8181043b26b5e79028
      os: linux
      sudo: required
      dist: trusty
    # Not a Salt node, runs test suite instead
    - env:
        - SALT_NODE_ID=test
      os: linux
      sudo: required
      dist: trusty

script: .travis/dispatch.sh

notifications:
  webhooks: http://build.servo.org:54856/travis
  irc: "irc.mozilla.org#servo-bots"

