# Python is not supported on OS X yet
# But a system python is installed for all workers
language: cpp

# NOTE: Make sure the matrix covers all node types in top.sls
# NOTE: Make sure each node type is tested both from scratch and as an upgrade
# sudo: required and dist: trusty enable usage of Trusty
matrix:
  include:
    # Salt from scratch
    - env:
        - SALT_NODE_ID=servo-linux-cross1
        - SALT_FROM_SCRATCH=true
      os: linux
      sudo: required
      dist: trusty
    - env:
        - SALT_NODE_ID=servo-mac1
        - SALT_FROM_SCRATCH=true
      os: osx
    - env:
        - SALT_NODE_ID=servo-linux1
        - SALT_FROM_SCRATCH=true
      os: linux
      sudo: required
      dist: trusty
    - env:
        - SALT_NODE_ID=servo-master1
        - SALT_FROM_SCRATCH=true
      os: linux
      sudo: required
      dist: trusty
      language: python
      python: 3.5
    # Salt from previous configuration
    - env:
        - SALT_NODE_ID=servo-linux-cross1
        - SALT_FROM_SCRATCH=false
      os: linux
      sudo: required
      dist: trusty
    - env:
        - SALT_NODE_ID=servo-mac1
        - SALT_FROM_SCRATCH=false
      os: osx
    - env:
        - SALT_NODE_ID=servo-linux1
        - SALT_FROM_SCRATCH=false
      os: linux
      sudo: required
      dist: trusty
    - env:
        - SALT_NODE_ID=servo-master1
        - SALT_FROM_SCRATCH=false
      os: linux
      sudo: required
      dist: trusty
      language: python
      python: 3.5
    # Not a Salt node, runs test suite instead
    - env:
        - SALT_NODE_ID=test
      os: linux
      sudo: required
      dist: trusty
      language: python
      python: 3.5

script: .travis/dispatch.sh

notifications:
  webhooks: http://build.servo.org:54856/travis
