[github]

# Information for securely interacting with GitHub. These are found/generated
# under <https://github.com/settings/applications>.

# A GitHub personal access token
access_token = "{{ pillar["homu"]["gh-access-token"] }}"

# A GitHub oauth application for this instance of homu:
app_client_id = "{{ pillar["homu"]["app-client-id"] }}"
app_client_secret = "{{ pillar["homu"]["app-client-secret"] }}"

[web]
port = 54856

{% set travis_repos = [('servo', 'html5ever'), ('servo', 'euclid'), ('servo', 'rust-layers'),
                       ('servo', 'saltfs'), ('servo', 'gleam'), ('servo', 'string-cache'),
                       ('servo', 'rust-selectors'), ('servo', 'rust-azure'), ('servo', 'tendril'),
                       ('servo', 'futf'), ('servo', 'glutin'), ('servo', 'rust-png'),
                       ('servo', 'rust-stb-image'), ('servo', 'libfreetype2'),
                       ('servo', 'libfontconfig'), ('servo', 'skia'), ('servo', 'cocoa-rs'),
                       ('servo', 'cgl-rs'), ('servo', 'io-surface-rs'), ('servo', 'rust-cssparser'),
                       ('servo', 'unicode-bidi'), ('servo', 'rust-smallvec'), ('servo', 'core-text-rs'),
                       ('servo', 'libexpat'), ('servo', 'rust-harfbuzz'), ('servo', 'heapsize'),
                       ('servo', 'rust-url'), ('servo', 'rust-freetype'), ('servo', 'fontsan')] %}
{% set buildbot_repos = [('servo', 'mozjs'), ('servo', 'rust-mozjs')] %}
{% set reviewers = ["glennw","jdm","kmcallister","larsbergstrom","Manishearth","metajack","mbrubeck","Ms2ger","pcwalton","SimonSapin","mrobinson","brunoabinader","saneyuki","nox","zmike","edunham","frewsxcv"] %}

[repo.servo]
owner = "servo"
name = "servo"
reviewers = {{ reviewers }}

[repo.servo.github]
secret = "{{ pillar["homu"]["gh-webhook-secret"] }}"

[repo.servo.buildbot]
url = "http://build.servo.org"
secret = "{{ pillar["homu"]["buildbot-secret"] }}"
builders = ["linux-dev", "linux-rel", "android", "mac-dev-ref-unit", "mac-rel-wpt", "mac-rel-css", "gonk"]
try_builders = ["linux-dev", "linux-rel", "android", "mac-dev-ref-unit", "mac-rel-wpt", "mac-rel-css", "gonk"]
username = "{{ pillar["homu"]["buildbot-http-user"] }}"
password = "{{ pillar["homu"]["buildbot-http-pass"] }}"

# Standard per-repo configs (generated)

{% for repo in travis_repos %}

[repo.{{ repo[1] }}]
owner = "{{ repo[0] }}"
name = "{{ repo[1] }}"
reviewers = {{ reviewers }}

[repo.{{ repo[1] }}.github]
secret = "{{ pillar["homu"]["gh-webhook-secret"] }}"

[repo.{{ repo[1] }}.travis]
token = "{{ pillar["homu"]["travis-ci-token"] }}"

{% endfor %}

{% for repo in buildbot_repos %}

[repo.{{ repo[1] }}]
owner = "{{ repo[0] }}"
name = "{{ repo[1] }}"
reviewers = {{ reviewers }}

[repo.{{ repo[1] }}.github]
secret = "{{ pillar["homu"]["gh-webhook-secret"] }}"

[repo.{{ repo[1] }}.buildbot]
url = "http://build.servo.org"
secret = "{{ pillar["homu"]["buildbot-secret"] }}"
builders = ["cargo-linux", "cargo-mac"]
try_builders = ["cargo-linux", "cargo-mac"]
username = "{{ pillar["homu"]["buildbot-http-user"] }}"
password = "{{ pillar["homu"]["buildbot-http-pass"] }}"

{% endfor %}

# Specialized per-repo configs

[repo.glutin.branch]
master = "servo"
